(function(){
'use strict';
const L=()=>document.body.classList.contains('lang-ht')?'ht':'en';
const T={required:{en:'Enter a valid name, email, and 10-digit phone.',ht:'Antre yon non, imel valab ak telefòn 10 chif.'},consent:{en:'Accept the contact and privacy notice.',ht:'Aksepte avi kontak ak konfidansyalite a.'},error:{en:'Delivery was not confirmed. Call or text (407) 267-2652.',ht:'Livrezon an pa konfime. Rele oswa ekri (407) 267-2652.'},success:{en:'Request received.',ht:'Nou resevwa demann nan.'}};
function styles(){const s=document.createElement('style');s.textContent='.reviews-grid,.rgrid,.reviews-header,.rev-head{display:none!important}.service-consent{display:block;margin:14px 0;font-size:.76rem;line-height:1.5;color:#667}.calculator-contact-cta{margin-top:18px;padding:18px;text-align:center;background:#f4eedf;border-radius:12px}.calculator-contact-cta p{margin-bottom:12px}.calculator-contact-cta a{display:inline-block;background:#c9a84c;color:#0b1d3a;text-decoration:none;font-weight:800;padding:11px 18px;border-radius:99px}.service-submit-status{margin-top:12px;padding:10px;border-radius:8px;font-size:.82rem}.service-submit-status.ok{background:#e7f6ec;color:#176b37}.service-submit-status.bad{background:#fff0ef;color:#9f2c25}';document.head.appendChild(s)}
function val(id){return String(document.getElementById(id)?.value||'').trim()}function email(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)}function phone(v){return v.replace(/\D/g,'').replace(/^1(?=\d{10}$)/,'')}
function consent(btn){if(btn.previousElementSibling?.classList.contains('service-consent'))return;const x=document.createElement('label');x.className='service-consent';x.innerHTML='<input type="checkbox" class="service-consent-check"> <span class="en">I confirm this review reflects my experience and authorize ME Shield to store, edit for length, and use it as a testimonial in website, story, social media, or marketing content. My email will remain private. See the <a href="privacy.html">Privacy Policy</a>.</span><span class="ht">Mwen konfime review sa a soti nan eksperyans mwen epi mwen bay ME Shield pèmisyon pou konsève li, rakousi li, epi itilize li kòm temwayaj sou website, story, rezo sosyal oswa marketing. Imel mwen ap rete prive. Gade <a href="privacy.html">Règleman Konfidansyalite</a>.</span>';btn.before(x)}
function status(btn,text,ok){let s=btn.parentNode.querySelector('.service-submit-status');if(!s){s=document.createElement('div');s.className='service-submit-status';btn.after(s)}s.textContent=text;s.className='service-submit-status '+(ok?'ok':'bad')}
async function send(btn,url,p){const old=btn.innerHTML;btn.disabled=true;btn.textContent=L()==='ht'?'Ap voye…':'Sending…';try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)}),j=await r.json();if(!r.ok||!j.success)throw 0;status(btn,T.success[L()]+' ID: '+j.submission_id,true)}catch(e){status(btn,T.error[L()],false)}finally{btn.disabled=false;btn.innerHTML=old}}
function calculatorsOnly(){const quoteCalls=['submitLead','submitTax','submitBiz','submitImm','submitIBC'];document.querySelectorAll('button[onclick]').forEach(btn=>{const call=(btn.getAttribute('onclick')||'').match(/^(submitLead|submitTax|submitBiz|submitImm|submitIBC)/)?.[1];if(!quoteCalls.includes(call))return;const fields=btn.parentNode.querySelector('.lead-form,.lfgrid');if(fields)fields.style.display='none';btn.style.display='none';const oldSuccess=btn.parentNode.querySelector('#calc-success,#tax-ok,#biz-ok,#imm-ok,#ibc-ok');if(oldSuccess)oldSuccess.style.display='none';const cta=document.createElement('div');cta.className='calculator-contact-cta';cta.innerHTML='<p class="en">This calculator does not collect or save your information. Need personalized help?</p><p class="ht">Kalkilatris sa a pa kolekte ni konsève enfòmasyon ou. Bezwen èd pèsonalize?</p><a class="service-book" href="book.html"><span class="en">Book Free Consultation</span><span class="ht">Rezève Konsiltasyon Gratis</span></a>';btn.after(cta)});}
function reviews(){document.querySelectorAll('button[onclick^="submitReview"]').forEach(btn=>{consent(btn);btn.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();if(!btn.parentNode.querySelector('.service-consent-check')?.checked){status(btn,T.consent[L()],false);return}const p={name:val('rv-name'),email:val('rv-email'),city:val('rv-city'),service:val('rv-service'),review:val('rv-text'),language:L(),website:''};if(p.name.length<2||!email(p.email)||p.review.length<10){status(btn,T.required[L()],false);return}send(btn,'/api/review',p)},true)})}
document.addEventListener('DOMContentLoaded',()=>{styles();calculatorsOnly();reviews()});
})();
